apply plugin: 'com.android.library'

android {
    compileSdkVersion Integer.parseInt(COMPILE_SDK_VERSION)

    defaultConfig {
        minSdkVersion Integer.parseInt(MIN_SDK_VERSION)
        targetSdkVersion Integer.parseInt(TARGET_SDK_VERSION)

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName()]
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }


    lintOptions {
        abortOnError false
    }
}

dependencies {
    annotationProcessor 'com.alibaba:arouter-compiler:1.5.2'
    api 'com.alibaba:arouter-annotation:1.0.6'
    implementation 'androidx.fragment:fragment:1.4.1'
}

apply from: rootProject.file('gradle/publish.gradle')